baseURL = 'https://goclub.space/'
languageCode = 'zh-cn'
title = 'GoClub'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  BookTheme = 'light'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookRepo = 'https://github.com/LeoninCS/GoClub'

[security]
  allowContent = ['^text/html$', '^text/markdown$']
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^node$', '^postcss$', '^tailwindcss$']
