name: 📝 提交面经
description: 直接提交面试记录
title: "[面经]投稿人-公司-岗位-几面"
labels:
  - question-submission
body:
  - type: dropdown
    id: company_category
    attributes:
      label: 请选择面经要收录的目录
      options:
        - 大厂
        - 中厂
        - 小厂
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        感谢投稿！
        请填写 issue 标题，网站会根据这个标题进行展示（可以匿名！）
        直接粘贴完整面试题目即可
        

  - type: textarea
    id: interview_content
    attributes:
      label: 面试内容
      description: 直接粘贴完整 Markdown。
      placeholder: |
        1. why
        2. where
        3. what
    validations:
      required: true

  - type: checkboxes
    id: submission_confirmation
    attributes:
      label: 投稿确认
      options:
        - label: 我确认内容不包含保密信息，不侵犯他人版权，且没有恶意链接或脚本。
          required: true
